config/routes.rb
Rails.application.routes.draw do
  namespace :backend do
    resources :notices
  end
  namespace :backend do
    resources :categories
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backend.rb
module Backend
  def self.table_name_prefix
    'backend_'
  end
end

app/models/backend/category.rb
class Backend::Category < ApplicationRecord
	has_many :backend_notices, class_name: "Backend::Notice", foreign_key:"backend_categories_id" 
end

app/models/backend/notice.rb
class Backend::Notice < ApplicationRecord
  belongs_to :backend_categories, class_name: "Backend::Category"
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :backend_notices, class_name: "Backend::Notice"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :first_name, :last_name, :userneme,
  				 :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < ApplicationController
  before_action :set_backend_category, only: [:show, :edit, :update, :destroy]

  # GET /backend/categories
  # GET /backend/categories.json
  def index
    @backend_categories = Backend::Category.all
  end

  # GET /backend/categories/1
  # GET /backend/categories/1.json
  def show
  end

  # GET /backend/categories/new
  def new
    @backend_category = Backend::Category.new
  end

  # GET /backend/categories/1/edit
  def edit
  end

  # POST /backend/categories
  # POST /backend/categories.json
  def create
    @backend_category = Backend::Category.new(backend_category_params)

    respond_to do |format|
      if @backend_category.save
        format.html { redirect_to @backend_category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @backend_category }
      else
        format.html { render :new }
        format.json { render json: @backend_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backend/categories/1
  # PATCH/PUT /backend/categories/1.json
  def update
    respond_to do |format|
      if @backend_category.update(backend_category_params)
        format.html { redirect_to @backend_category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @backend_category }
      else
        format.html { render :edit }
        format.json { render json: @backend_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/categories/1
  # DELETE /backend/categories/1.json
  def destroy
    @backend_category.destroy
    respond_to do |format|
      format.html { redirect_to backend_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backend_category
      @backend_category = Backend::Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backend_category_params
      params.require(:backend_category).permit(:title)
    end
end

app/controllers/backend/notices_controller.rb
class Backend::NoticesController < ApplicationController
  before_action :set_backend_notice, only: [:show, :edit, :update, :destroy]

  # GET /backend/notices
  # GET /backend/notices.json
  def index
    @backend_notices = Backend::Notice.all
  end

  # GET /backend/notices/1
  # GET /backend/notices/1.json
  def show
  end

  # GET /backend/notices/new
  def new
    @backend_notice = Backend::Notice.new
  end

  # GET /backend/notices/1/edit
  def edit
  end

  # POST /backend/notices
  # POST /backend/notices.json
  def create
    @backend_notice = Backend::Notice.new(backend_notice_params)
    #@backend_notice = current_user.backend_notice.build(backend_notice_params)
    respond_to do |format|
      if @backend_notice.save
        format.html { redirect_to @backend_notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @backend_notice }
      else
        format.html { render :new }
        format.json { render json: @backend_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backend/notices/1
  # PATCH/PUT /backend/notices/1.json
  def update
    respond_to do |format|
      if @backend_notice.update(backend_notice_params)
        format.html { redirect_to @backend_notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @backend_notice }
      else
        format.html { render :edit }
        format.json { render json: @backend_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backend/notices/1
  # DELETE /backend/notices/1.json
  def destroy
    @backend_notice.destroy
    respond_to do |format|
      format.html { redirect_to backend_notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backend_notice
      @backend_notice = Backend::Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backend_notice_params
      params.require(:backend_notice).permit(:backend_categories_id, :title, :content, :user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/categories_helper.rb
module Backend::CategoriesHelper
end

app/helpers/backend/notices_helper.rb
module Backend::NoticesHelper
end

app/views/backend/categories/_form.html.slim
= form_for @backend_category do |f|
  - if @backend_category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@backend_category.errors.count, "error")} prohibited this backend_category from being saved:"
      ul
        - @backend_category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .actions = f.submit

app/views/backend/categories/edit.html.slim
h1 Editing backend_category

== render 'form'

=> link_to 'Show', @backend_category
'|
=< link_to 'Back', backend_categories_path

app/views/backend/categories/index.html.slim
h1 Listing backend_categories

table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @backend_categories.each do |backend_category|
      tr
        td = backend_category.title
        td = link_to 'Show', backend_category
        td = link_to 'Edit', edit_backend_category_path(backend_category)
        td = link_to 'Destroy', backend_category, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Category', new_backend_category_path

app/views/backend/categories/new.html.slim
h1 New backend_category

== render 'form'

= link_to 'Back', backend_categories_path

app/views/backend/categories/show.html.slim
p#notice = notice

p
  strong Title:
  = @backend_category.title

=> link_to 'Edit', edit_backend_category_path(@backend_category)
'|
=< link_to 'Back', backend_categories_path

app/views/backend/notices/_form.html.slim
= form_for @backend_notice do |f|
  - if @backend_notice.errors.any?
    #error_explanation
      h2 = "#{pluralize(@backend_notice.errors.count, "error")} prohibited this backend_notice from being saved:"
      ul
        - @backend_notice.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :backend_categories
    = f.text_field :backend_categories
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions = f.submit

app/views/backend/notices/edit.html.slim
h1 Editing backend_notice

== render 'form'

=> link_to 'Show', @backend_notice
'|
=< link_to 'Back', backend_notices_path

app/views/backend/notices/index.html.slim
h1 Listing backend_notices

table
  thead
    tr
      th Backend categories
      th Title
      th Content
      th
      th
      th

  tbody
    - @backend_notices.each do |backend_notice|
      tr
        td = backend_notice.backend_categories
        td = backend_notice.title
        td = backend_notice.content
        td = link_to 'Show', backend_notice
        td = link_to 'Edit', edit_backend_notice_path(backend_notice)
        td = link_to 'Destroy', backend_notice, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Notice', new_backend_notice_path

app/views/backend/notices/new.html.slim
h1 New backend_notice

== render 'form'

= link_to 'Back', backend_notices_path

app/views/backend/notices/show.html.slim
p#notice = notice

p
  strong Backend categories:
  = @backend_notice.backend_categories
p
  strong Title:
  = @backend_notice.title
p
  strong Content:
  = @backend_notice.content

=> link_to 'Edit', edit_backend_notice_path(@backend_notice)
'|
=< link_to 'Back', backend_notices_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notiblogv2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>